<?php

namespace Idestru\MMCrmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientOrderRepository extends EntityRepository
{
}
